Repository FordLabs/PeopleMover, pull requests merged in 2020-12, with the labels that each got.

#589 Revise error handling
  ui/cypress/e2e/api_errors.test.js
  ui/cypress/e2e/people.test.js
  ui/src/Application/PeopleMover.tsx
  ui/src/Auth/AuthenticatedRoute.tsx
  ui/src/Login/AccessTokenClient.ts
  ui/src/ModalFormComponents/Select.test.tsx
  ui/src/People/People.test.tsx
  ui/src/SpaceDashboard/SpaceDashboard.test.tsx
  ui/src/SpaceDashboard/SpaceDashboard.tsx
  ui/src/index.tsx
  ui/src/tests/ArchivedProduct.test.tsx
  ui/src/tests/FilterProducts.test.tsx
  ui/src/tests/LocalStorageFilters.test.tsx
  ui/src/tests/PeopleMover.test.tsx
  ui/src/tests/Product.test.tsx
  ui/src/tests/ProductList.test.tsx
  ui/src/tests/Unassigned.test.tsx
  ui/src/tests/ValidationGuard.test.tsx
Labels: Dev Approved, No design review needed

#588 Add meta.json and cachebusting
  .github/workflows/build.yml
  ui/generate-build-version.js
  ui/package-lock.json
  ui/package.json
  ui/public/meta.json
  ui/src/CacheBuster.jsx
  ui/src/Routes.tsx
  ui/src/index.tsx
Labels: Dev Approved, No design review needed

#592 Remove matomo events for unauthorize
  ui/src/index.tsx
  ui/webpack.config.js
Labels: No design review needed

#593 62 Update Matomo error convention naming and add error events
  ui/src/Assignments/AssignmentCard.tsx
  ui/src/Products/ProductClient.ts
  ui/src/ReassignedDrawer/ReassignedDrawer.tsx
  ui/src/Space/SpaceClient.ts
  ui/src/index.tsx
Labels: No design review needed, Same Same

#595 Ensure calendar updates with highlighted dates
  ui/cypress/e2e/people.test.js
  ui/src/Calendar/Calendar.tsx
  ui/src/ReassignedDrawer/ReassignedDrawer.tsx
Labels: Dev Approved, No design review needed

#596 Add person notes to people report download
  api/src/main/kotlin/com/ford/internalprojects/peoplemover/report/PeopleReportRow.kt
  api/src/main/kotlin/com/ford/internalprojects/peoplemover/report/ReportGeneratorService.kt
  api/src/test/kotlin/com/ford/internalprojects/peoplemover/report/ReportGeneratorControllerTest.kt
  ui/src/Reports/ReportClient.test.tsx
  ui/src/Reports/ReportClient.ts
Labels: Dev Approved, No design review needed

#597 Remove reload from cache buster to avoid endless reload loop
  ui/src/CacheBuster.jsx
Labels: Dev Approved, No design review needed

#594 Add custom note hovering css for people in unassigned
  ui/src/Assignments/AssignmentCard.test.tsx
  ui/src/Assignments/PersonAndRoleInfo.scss
  ui/src/Assignments/PersonAndRoleInfo.tsx
  ui/src/Assignments/PersonDrawer.scss
  ui/src/Assignments/UnassignedDrawer.tsx
Labels: Design Approved, Dev Approved
