Repository FordLabs/PeopleMover, pull requests merged in 2021-02, with the labels that each got.

#621 Fix margin issue for space name in dashboard
  ui/src/SpaceDashboard/SpaceDashboardTile.scss
Labels: Design Approved

#622 Gray out text on Add New Product button when in read only space
  .guet/committers
  ui/src/Products/NewProductButton.scss
Labels: Design Approved

#626 Accessibility assign focus trap
  ui/package-lock.json
  ui/package.json
  ui/src/Modal/Modal.tsx
  ui/src/tests/FilterProducts.test.tsx
Labels: Ready for Design Review

#627 Confirmation modal bug
  ui/src/Modal/ConfirmationModal.tsx
  ui/src/tests/FilterProducts.test.tsx
Labels: Design Approved

#634 Add list of current editors
  api/src/main/kotlin/com/ford/internalprojects/peoplemover/auth/UserSpaceMappingRepository.kt
  api/src/main/kotlin/com/ford/internalprojects/peoplemover/space/SpaceController.kt
  api/src/main/kotlin/com/ford/internalprojects/peoplemover/space/SpaceService.kt
  api/src/main/resources/db/mysql/V015__remove_extra_space_from_user_id.sql
  api/src/test/kotlin/com/ford/internalprojects/peoplemover/space/SpaceControllerApiTest.kt
  ui/cypress/e2e/share_access_form.test.js
  ui/src/AccountDropdown/InviteEditorsFormSection.scss
  ui/src/AccountDropdown/InviteEditorsFormSection.test.tsx
  ui/src/AccountDropdown/InviteEditorsFormSection.tsx
  ui/src/Space/SpaceClient.test.tsx
  ui/src/Space/SpaceClient.ts
  ui/src/tests/TestUtils.tsx
Labels: Design Approved

#635 Add logic to be able to copy name and role of person while in read on…
  ui/src/Assignments/PersonAndRoleInfo.scss
  ui/src/Assignments/PersonAndRoleInfo.tsx
Labels: No dev review needed, Ready for Design Review
