Repository FordLabs/PeopleMover, pull requests merged in 2021-01, with the labels that each got.

#598 Update Dropdowns options
  ui/cypress/e2e/form_field_dropdowns.test.js
  ui/cypress/e2e/people.test.js
  ui/cypress/support/commands.js
  ui/src/Assignments/AssignmentForm.scss
  ui/src/Assignments/AssignmentForm.test.tsx
  ui/src/Assignments/AssignmentForm.tsx
  ui/src/CommonTypes/Option.ts
  ui/src/ModalFormComponents/EditTagRow.tsx
  ui/src/ModalFormComponents/ReactSelectStyles.scss
  ui/src/ModalFormComponents/ReactSelectStyles.tsx
  ui/src/ModalFormComponents/SelectWithCreateOption.tsx
  ui/src/ModalFormComponents/SelectWithHTMLOptions.scss
  ui/src/ModalFormComponents/SelectWithHTMLOptions.test.tsx
  ui/src/ModalFormComponents/SelectWithHTMLOptions.tsx
  ui/src/ModalFormComponents/SelectWithNoCreateOption.test.tsx
  ui/src/ModalFormComponents/SelectWithNoCreateOption.tsx
  ui/src/People/People.test.tsx
  ui/src/People/PersonForm.tsx
  ui/src/Products/ProductForm.test.tsx
  ui/src/Products/ProductForm.tsx
  ui/src/Products/ProductFormLocationField.tsx
  ui/src/Products/ProductFormProductTagsField.tsx
  ui/src/ReusableComponents/ProductFilter.tsx
  ui/src/ReusableComponents/ProductSortBy.tsx
  ui/src/Roles/ColorDropdown.tsx
  ui/src/tests/FilterProducts.test.tsx
  ui/src/tests/MultiSelect.test.tsx
  ui/src/tests/Product.test.tsx
Labels: Design Approved, Dev Approved

#601 Add branding to the landing page and space dashboard
  ui/src/Application/Assets/fordlabs_logo.svg
  ui/src/LandingPage/LandingPage.scss
  ui/src/LandingPage/LandingPage.tsx
  ui/src/SpaceDashboard/SpaceDashboard.scss
  ui/src/SpaceDashboard/SpaceDashboard.tsx
Labels: Design Approved, Ready for Dev Review

#602 Change verbage to create tags in dropdown and fix focus state styling
  ui/cypress/e2e/form_field_dropdowns.test.js
  ui/src/Assignments/AssignmentForm.test.tsx
  ui/src/ModalFormComponents/ReactSelectStyles.tsx
  ui/src/ModalFormComponents/SelectWithNoCreateOption.tsx
  ui/src/People/People.test.tsx
  ui/src/tests/FilterProducts.test.tsx
  ui/src/tests/Product.test.tsx
  ui/src/tests/TestUtils.tsx
Labels: No dev review needed, Ready for Design Review

#603 Update styling on 404 page
  ui/src/Application/Error404Page.scss
  ui/src/Application/Error404Page.tsx
Labels: Design Approved

#605 Add isDragging to redux to not show notes while dragging
  ui/src/Assignments/AssignmentCard.test.tsx
  ui/src/Assignments/AssignmentCardList.tsx
  ui/src/Assignments/PersonAndRoleInfo.tsx
  ui/src/Redux/Actions/index.ts
  ui/src/Redux/Reducers/index.ts
  ui/src/Redux/Reducers/isDraggingReducer.ts
Labels: Design Approved, Dev Approved

#604 Make 403 error page
  ui/src/Application/Assets/403.png
  ui/src/Application/ErrorPageTemplate.scss
  ui/src/Application/ErrorPageTemplate.tsx
  ui/src/Routes.tsx
Labels: Ready for Design Review

#607 redirect to 403 & 404page
  api/src/main/kotlin/com/ford/internalprojects/peoplemover/auth/AuthController.kt
  api/src/test/kotlin/com/ford/internalprojects/peoplemover/auth/AuthControllerTest.kt
  ui/public/meta.json
  ui/src/Application/PeopleMover.tsx
  ui/src/Auth/AuthorizedRoute.tsx
  ui/src/tests/AuthorizedRoute.test.tsx
  ui/src/tests/PeopleMover.test.tsx
Labels: Dev Approved

#606 Landing Page Accessibility
  ui/src/Application/ErrorPageTemplate.tsx
  ui/src/Application/PeopleMover.tsx
  ui/src/LandingPage/LandingPage.scss
  ui/src/LandingPage/LandingPage.tsx
  ui/src/ReusableComponents/Branding.tsx
  ui/src/ReusableComponents/PeopleMoverLogo.scss
  ui/src/ReusableComponents/PeopleMoverLogo.tsx
  ui/src/SpaceDashboard/SpaceDashboard.tsx
  ui/src/UnsupportedBrowserPage/UnsupportedBrowserPage.tsx
Labels: Ready for Design Review

#611 View only by space
  api/src/main/kotlin/com/ford/internalprojects/peoplemover/TestConfig.kt
  api/src/main/kotlin/com/ford/internalprojects/peoplemover/auth/AuthInterceptor.kt
  api/src/main/kotlin/com/ford/internalprojects/peoplemover/space/EditSpaceRequest.kt
  api/src/main/kotlin/com/ford/internalprojects/peoplemover/space/Space.kt
  api/src/main/kotlin/com/ford/internalprojects/peoplemover/space/SpaceController.kt
  api/src/main/kotlin/com/ford/internalprojects/peoplemover/space/SpaceService.kt
  api/src/test/kotlin/com/ford/internalprojects/peoplemover/assignment/AssignmentControllerInTimeApiTest.kt
  api/src/test/kotlin/com/ford/internalprojects/peoplemover/assignment/AssignmentControllerReassignmentsApiTest.kt
  api/src/test/kotlin/com/ford/internalprojects/peoplemover/location/LocationControllerApiTest.kt
  api/src/test/kotlin/com/ford/internalprojects/peoplemover/person/PersonControllerApiTest.kt
  api/src/test/kotlin/com/ford/internalprojects/peoplemover/product/ProductControllerApiTest.kt
  api/src/test/kotlin/com/ford/internalprojects/peoplemover/product/ProductControllerInTimeApiTest.kt
  api/src/test/kotlin/com/ford/internalprojects/peoplemover/producttag/ProductTagControllerTest.kt
  api/src/test/kotlin/com/ford/internalprojects/peoplemover/role/RoleControllerApiTest.kt
  api/src/test/kotlin/com/ford/internalprojects/peoplemover/space/SpaceControllerApiTest.kt
  ui/cypress/e2e/account_dropdown.test.js
  ui/package-lock.json
  ui/package.json
  ui/src/AccountDropdown/EditContributorsForm.scss
  ui/src/AccountDropdown/EditContributorsForm.test.tsx
  ui/src/AccountDropdown/EditContributorsForm.tsx
  ui/src/AccountDropdown/InviteContributorsConfirmationModal.scss
  ui/src/Space/Space.ts
  ui/src/tests/CurrentSpaceReducer.test.ts
  ui/src/tests/TestUtils.tsx
Labels: Design Approved

#617 Accessibility focus state flow
  ui/src/AccountDropdown/AccountDropdown.tsx
  ui/src/Assignments/AssignmentCard.scss
  ui/src/Assignments/AssignmentCard.tsx
  ui/src/Calendar/Calendar.scss
  ui/src/Calendar/CalendarInputLabel.tsx
  ui/src/Header/SpaceSelectionTabs.scss
  ui/src/Header/SpaceSelectionTabs.tsx
  ui/src/ModalFormComponents/ReactSelectStyles.tsx
  ui/src/Products/NewProductButton.scss
  ui/src/Products/NewProductButton.tsx
  ui/src/Products/ProductCard.tsx
  ui/src/ReassignedDrawer/ReassignedDrawer.scss
  ui/src/ReassignedDrawer/ReassignedDrawer.tsx
  ui/src/ReusableComponents/DrawerContainer.scss
  ui/src/ReusableComponents/DrawerContainer.tsx
  ui/src/ReusableComponents/ProductFilter.tsx
  ui/src/ReusableComponents/ProductSortBy.tsx
  ui/src/ReusableComponents/ThemeApplier.ts
  ui/src/tests/PeopleMover.test.tsx
Labels: Ready for Design Review
